export const GET_IMAGES = "GET_IMAGES";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_FAIL = "GET_IMAGES_FAIL";
export const SET_SELECTED_IMAGE = "SET_SELECTED_IMAGE";
export const CLEAR_SELECTED_IMAGE = "CLEAR_SELECTED_IMAGE";
